language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - python-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev
      - libunbound-dev:i386

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

env:
  - DPDK=1 OPTS="--enable-shared"
  - TESTSUITE=1 DPDK=1
  - DPDK_SHARED=1
  - DPDK_SHARED=1 OPTS="--enable-shared"

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - ovs-build@openvswitch.org
